spring:
  application:
    name: mono-wnt

  datasource:
    url: jdbc:postgresql://localhost:5432/mono_wnt_db
    username: wnt_user
    password: test1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  sql:
#    init:
#      mode: always

logging:
  level:
    org.hibernate.SQL: DEBUG                # 실행되는 SQL (DDL/DML)
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.tool.schema: DEBUG

jwt:
  secret:
    key: qwdhui83jvnllw133EJBCA712jnfe982329H#p219qnf43yj90j32
  expiration:
    time: 7200000