spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mono_wnt_db
    username: wnt_user
    password: test1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    defer-datasource-initialization: true
    open-in-view: false

  sql:
    init:
      mode: always
      data-locations:
        - classpath:sql/001_store_data.sql
      continue-on-error: false
      encoding: UTF-8

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret:
    key: qwdhui83jvnllw133EJBCA712jnfe982329H#p219qnf43yj90j32
  expiration:
    time: 7200000

cloud:
  aws:
    credentials:
      access-key: aaaaaaaaaaaaaa
      secret-key: aaaaaaaaaaaaa
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: "{}"
      url:
        default: "https://{}.s3.ap-northeast-2.amazonaws.com/"
        uploaded: "https://{}.s3.ap-northeast-2.amazonaws.com/"