spring:
  config:
    import:
      - classpath:/secret/application-cloud.yml
      - classpath:/secret/application-db.yml
      - classpath:/secret/application-variable.yml

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
